version: '2'
services:
  webapp:
      build:
        context: .
        dockerfile: webapp.Dockerfile
      hostname: samplewebapp
      container_name: mywebapp

  tomcat:
      build:
        context: .
        dockerfile: tomcat.Dockerfile
      hostname: kamyshevtomcat
      container_name: tomcat
#      ports: [ "8080:80" ]







  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    hostname: kamyshevnginx
    container_name: mynginx
    ports: [ "80:80" ]
