version: '2'
services:

  tomcat:
      build:
        context: .
        dockerfile: ./tomcat.Dockerfile
      image: mytomcat
      container_name: mytomcat


  nginx:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    container_name: mynginx
    image: mynginx
    ports: [ "80:80" ]
    depends_on:
      - "webapp"

  webapp:
      build:
        context: .
        dockerfile: ./webapp.Dockerfile
      container_name: mywebapp
      image: mywebapp
      depends_on:
        - "tomcat"
