version: '2'
services:

  tomcat1:
      build:
        context: .
        dockerfile: ./tomcat.Dockerfile
      image: mytomcat
      command: echo

  tomcat:
      build:
        context: .
        dockerfile: ./tomcat.Dockerfile
      image: mytomcat
      container_name: mytomcat
      volumes_from:
        - "webapp"
      depends_on:
        - "webapp"


  nginx:
      build:
        context: .
        dockerfile: ./nginx.Dockerfile
      container_name: mynginx
      image: mynginx
      ports: [ "80:80" ]
      depends_on:
        - "tomcat"

  webapp:
      build:
        context: .
        dockerfile: ./webapp.Dockerfile
      container_name: mywebapp
      image: mywebapp
      depends_on:
        - "tomcat1"
