version: '2'
services:
 ansible:
    build:
         context: .
         dockerfile: ansible.Dockerfile
    container_name: ansible-data


 gradle:
    build:
         context: .
         dockerfile: gradle.Dockerfile
    container_name: gradle-data
